dw_marketing:
  outputs:
    prod:
      dbname: "dw_marketing"
      host: "{{env_var('DB_HOST_PROD')}}"
      password: "{{env_var('DB_PASS_PROD')}}"
      port: "{{env_var('DB_PORT_PROD') | int}}"
      user: "{{env_var('DB_USER_PROD')}}"
      schema: "{{env_var('DB_SCHEMA_PROD')}}"
      threads: "{{env_var('DB_THREADS_PROD') | int}}"
      type: postgres
  target: prod